---
- name:  Copy kubernetes yum.repo
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo
  when: local_install == "no"

- name:  Copy k8s.sh
  copy: src=k8s.sh dest=/root/xcloud/ mode=777
  when: local_install == "no"

- name: Install kubeadm kubelet kubectl
  shell: ./k8s.sh {{kubernetes_version}} chdir=/root/xcloud
  when: local_install == "no"

- name:  Copying over k8s.conf files for k8s
  copy: src=k8s.conf dest=/etc/sysctl.d/k8s.conf

- name: Apply the sysctl
  command: sysctl --system

- name: service daemon-reload
  command: systemctl daemon-reload

- name: Start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

