---
- name: Copy flannel.yaml
  template:
    src: kube-flannel.yml.j2
    dest: /root/xcloud/kube-flannel-1.12.2.yml
  run_once: True
  delegate_to: "{{groups['kubernetes-master'][0]}}"

- name: Delete flannel
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl delete -f  /root/xcloud/kube-flannel-1.12.2.yml
  run_once: True
  delegate_to: "{{groups['kubernetes-master'][0]}}"
  ignore_errors: yes
